[2024-10-30T09:15:57.887+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-30T09:15:57.912+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:15:54.050154+00:00 [queued]>
[2024-10-30T09:15:57.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:15:54.050154+00:00 [queued]>
[2024-10-30T09:15:57.922+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-30T09:15:57.934+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_date_stage> on 2024-10-30 09:15:54.050154+00:00
[2024-10-30T09:15:57.940+0000] {standard_task_runner.py:63} INFO - Started process 13372 to run task
[2024-10-30T09:15:57.943+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'load_date_stage', 'manual__2024-10-30T09:15:54.050154+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpczij2rqq']
[2024-10-30T09:15:57.944+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask load_date_stage
[2024-10-30T09:15:57.984+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.load_date_stage manual__2024-10-30T09:15:54.050154+00:00 [running]> on host 3d0ab7361361
[2024-10-30T09:15:58.248+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='load_date_stage' AIRFLOW_CTX_EXECUTION_DATE='2024-10-30T09:15:54.050154+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-30T09:15:54.050154+00:00'
[2024-10-30T09:15:58.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-30T09:15:58.255+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-30T09:15:58.256+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'xlrd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/Date/LoadDate.py", line 6, in read_date_excel
    time_df = pd.read_excel('/opt/airflow/data/SampleDateDim.xls', sheet_name='LoadDates')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/io/excel/_xlrd.py", line 44, in __init__
    import_optional_dependency("xlrd", extra=err_msg)
  File "/home/airflow/.local/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.
[2024-10-30T09:15:58.272+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL_To_Data_Warehouse, task_id=load_date_stage, run_id=manual__2024-10-30T09:15:54.050154+00:00, execution_date=20241030T091554, start_date=20241030T091557, end_date=20241030T091558
[2024-10-30T09:15:58.289+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 114 for task load_date_stage (Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.; 13372)
[2024-10-30T09:15:58.317+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-30T09:15:58.338+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T09:15:58.342+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
