[2024-11-13T01:36:10.866+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T01:36:10.900+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgBenef manual__2024-11-13T01:35:32.452574+00:00 [queued]>
[2024-11-13T01:36:10.910+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgBenef manual__2024-11-13T01:35:32.452574+00:00 [queued]>
[2024-11-13T01:36:10.911+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T01:36:10.924+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clear_data_to_stgBenef> on 2024-11-13 01:35:32.452574+00:00
[2024-11-13T01:36:10.930+0000] {standard_task_runner.py:63} INFO - Started process 3408 to run task
[2024-11-13T01:36:10.933+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'clear_data_to_stgBenef', 'manual__2024-11-13T01:35:32.452574+00:00', '--job-id', '770', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmphigslhsw']
[2024-11-13T01:36:10.934+0000] {standard_task_runner.py:91} INFO - Job 770: Subtask clear_data_to_stgBenef
[2024-11-13T01:36:10.988+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.clear_data_to_stgBenef manual__2024-11-13T01:35:32.452574+00:00 [running]> on host 3d0ab7361361
[2024-11-13T01:36:11.367+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='clear_data_to_stgBenef' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T01:35:32.452574+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T01:35:32.452574+00:00'
[2024-11-13T01:36:11.368+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T01:36:11.428+0000] {logging_mixin.py:188} WARNING - /opt/***/plugins/NCC/clear_data_stgBenef.py:16 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-11-13T01:36:15.350+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-13T01:36:15.351+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T01:36:15.360+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=clear_data_to_stgBenef, run_id=manual__2024-11-13T01:35:32.452574+00:00, execution_date=20241113T013532, start_date=20241113T013610, end_date=20241113T013615
[2024-11-13T01:36:15.401+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-13T01:36:15.607+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T01:36:15.609+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
