[2024-11-05T16:05:24.351+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-05T16:05:24.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.start manual__2024-11-05T16:05:22.767554+00:00 [queued]>
[2024-11-05T16:05:24.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_To_Data_Warehouse.start manual__2024-11-05T16:05:22.767554+00:00 [queued]>
[2024-11-05T16:05:24.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-05T16:05:24.395+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start> on 2024-11-05 16:05:22.767554+00:00
[2024-11-05T16:05:24.402+0000] {standard_task_runner.py:63} INFO - Started process 20381 to run task
[2024-11-05T16:05:24.404+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_To_Data_Warehouse', 'start', 'manual__2024-11-05T16:05:22.767554+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/ETL_LDTBXH.dag.py', '--cfg-path', '/tmp/tmpfjrzxcjq']
[2024-11-05T16:05:24.405+0000] {standard_task_runner.py:91} INFO - Job 329: Subtask start
[2024-11-05T16:05:24.449+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_To_Data_Warehouse.start manual__2024-11-05T16:05:22.767554+00:00 [running]> on host 3d0ab7361361
[2024-11-05T16:05:24.769+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_To_Data_Warehouse' AIRFLOW_CTX_TASK_ID='start' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T16:05:22.767554+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T16:05:22.767554+00:00'
[2024-11-05T16:05:24.770+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-05T16:05:24.771+0000] {logging_mixin.py:188} INFO - Starting ETL process to DATA WAREHOUSE...
[2024-11-05T16:05:24.771+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-05T16:05:24.772+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-05T16:05:24.780+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_To_Data_Warehouse, task_id=start, run_id=manual__2024-11-05T16:05:22.767554+00:00, execution_date=20241105T160522, start_date=20241105T160524, end_date=20241105T160524
[2024-11-05T16:05:24.818+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-05T16:05:24.838+0000] {dagrun.py:940} ERROR - Failed to get task for ti <TaskInstance: ETL_To_Data_Warehouse.load_data_to_Stg_BaoCaoNCC_Fact manual__2024-11-05T16:05:22.767554+00:00 [None]>. Marking it as removed.
[2024-11-05T16:05:25.056+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-05T16:05:25.058+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
